# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181226_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='time_now',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 26, 14, 20, 13, 882008, tzinfo=utc)),
        ),
    ]
