# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181228_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='time_now',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 28, 7, 38, 3, 885270, tzinfo=utc)),
        ),
    ]
