# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 04:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181230_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='time_now',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 1, 4, 3, 25, 390050, tzinfo=utc)),
        ),
    ]
