# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 05:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190101_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='time_now',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 1, 5, 34, 37, 644365, tzinfo=utc)),
        ),
    ]
