# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190101_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_detail',
            name='time_now',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 1, 6, 31, 44, 116969, tzinfo=utc)),
        ),
    ]
